# Generated by Django 5.2 on 2026-05-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Castellà'), ('en', 'Anglès'), ('fr', 'Francès')], default='ca', help_text='Idioma per a la lectura en veu alta (TTS) dels ítems', max_length=2),
        ),
    ]
