# Generated by Django 5.2 on 2026-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
    ]
