# Generated by Django 5.2 on 2026-04-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tried',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tried_items', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='tried',
            name='identifiedItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_items', to='catalog.item'),
        ),
    ]
